### ISSUE TITLE
Allow deletion of EphemeralHybridMessage

### ISSUE THREAD

**Issue by russellbanks** [qbosst/kordex-hybrid-commands#2]
With hybrid messages, there are two possible message responses that can be created: a chat response and a slash response. In the case of `PublicHybridMessage`, both can be deleted as they are public. With `EphemeralHybridMessage`, neither can currently be deleted. This makes sense with ephemeral responses as they can only be seen to the user. However, the chat response will always be public regardless of whether its slash counterpart is ephemeral or not.

Therefore, the ideal functionality would be that running `EphemeralHybridMessage.delete()` would delete its chat counterpart.

**Comment by bosukas** [comment]
Hi, I've added `EphemeralHybridMessage.delete()`, test it out and let me know if it suits your needs.
It's on the snapshot version so you don't need to change anything with your dependencies.

Thanks

**Comment by russellbanks** [comment]
Hey, I've tested the `EphemeralHybridMessage.delete()` and it works great, thank you :)
