### ISSUE TITLE
Not compatible with Kordex 1.5.5-SNAPSHOT

### ISSUE THREAD

**Issue by Glennmen** [qbosst/kordex-hybrid-commands#3]
I tried to use this in my project but it seems that it is not compatible with the latest snapshot version.

I needed the latest snapshot because I wanted to use `allowInDms = false`.
But during build I am getting the following error:
`Exception in thread "main" java.lang.IncompatibleClassChangeError: class io.github.qbosst.kordex.commands.hybrid.AbstractHybridCommand overrides final method com.kotlindiscord.kord.extensions.commands.Command.getTranslationsProvider()Lcom/kotlindiscord/kord/extensions/i18n/TranslationsProvider;
`

**Comment by bosukas** [comment]
Hi, 
thanks for making an issue, 

I'll update hybrid commands to be compatible with kord-ex by the end of the week.
My schedule has been quite busy. If you need it urgently you could make a PR for it
